package com.dream.dao;

import java.util.List;

import com.dream.bean.Area;

public interface AreaMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int deleteByPrimaryKey(Integer areaid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int insert(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int insertSelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	Area selectByPrimaryKey(Integer areaid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int updateByPrimaryKeySelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table area
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int updateByPrimaryKey(Area record);

	// ******************add by wsg**********************

	/**
	 * 根据条件查询，返回一个对象
	 * 
	 * @param area
	 * @return
	 */
	Area detailArea(Area area);

	/**
	 * 根据条件查询，返回一个list
	 * 
	 * @param area
	 * @return
	 */
	List<Area> listArea(Area area);
}