package com.dream.dao;

import java.util.List;

import com.dream.bean.Store;

public interface StoreMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int deleteByPrimaryKey(Integer storeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int insert(Store record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int insertSelective(Store record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	Store selectByPrimaryKey(Integer storeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int updateByPrimaryKeySelective(Store record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table store
	 * 
	 * @mbggenerated Tue Sep 23 17:45:35 CST 2014
	 */
	int updateByPrimaryKey(Store record);

	// ******************add by wsg**********************
	/**
	 * 根据条件返回一个对象
	 * 
	 * @param store
	 * @return
	 */
	Store detailStore(Store store);

	/**
	 * 根据条件返回一个list
	 * 
	 * @param store
	 * @return
	 */

	List<Store> listStore(Store store);
}