package com.dream.bean;

public class Commodity extends BaseBean  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityname
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commodityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityprice
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commodityprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commoditydetail
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commoditydetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commoditypic
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commoditypic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.committime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String committime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.lastupdatetime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.kindsid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer kindsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.counter
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer counter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.suggestLev
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer suggestlev;
    
    //************************
    /**
     * 排序字段
     */
    private String order ; 
    

    public String getOrder() {
		return order;
	}

	public void setOrder(String order) {
		this.order = order;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityid
     *
     * @return the value of commodity.commodityid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityid
     *
     * @param commodityid the value for commodity.commodityid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityname
     *
     * @return the value of commodity.commodityname
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityname
     *
     * @param commodityname the value for commodity.commodityname
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname == null ? null : commodityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityprice
     *
     * @return the value of commodity.commodityprice
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommodityprice() {
        return commodityprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityprice
     *
     * @param commodityprice the value for commodity.commodityprice
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommodityprice(String commodityprice) {
        this.commodityprice = commodityprice == null ? null : commodityprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commoditydetail
     *
     * @return the value of commodity.commoditydetail
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommoditydetail() {
        return commoditydetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commoditydetail
     *
     * @param commoditydetail the value for commodity.commoditydetail
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommoditydetail(String commoditydetail) {
        this.commoditydetail = commoditydetail == null ? null : commoditydetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commoditypic
     *
     * @return the value of commodity.commoditypic
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommoditypic() {
        return commoditypic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commoditypic
     *
     * @param commoditypic the value for commodity.commoditypic
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommoditypic(String commoditypic) {
        this.commoditypic = commoditypic == null ? null : commoditypic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.committime
     *
     * @return the value of commodity.committime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommittime() {
        return committime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.committime
     *
     * @param committime the value for commodity.committime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommittime(String committime) {
        this.committime = committime == null ? null : committime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.lastupdatetime
     *
     * @return the value of commodity.lastupdatetime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.lastupdatetime
     *
     * @param lastupdatetime the value for commodity.lastupdatetime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setLastupdatetime(String lastupdatetime) {
        this.lastupdatetime = lastupdatetime == null ? null : lastupdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.kindsid
     *
     * @return the value of commodity.kindsid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getKindsid() {
        return kindsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.kindsid
     *
     * @param kindsid the value for commodity.kindsid
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setKindsid(Integer kindsid) {
        this.kindsid = kindsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.counter
     *
     * @return the value of commodity.counter
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.counter
     *
     * @param counter the value for commodity.counter
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCounter(Integer counter) {
        this.counter = counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.suggestLev
     *
     * @return the value of commodity.suggestLev
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getSuggestlev() {
        return suggestlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.suggestLev
     *
     * @param suggestlev the value for commodity.suggestLev
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setSuggestlev(Integer suggestlev) {
        this.suggestlev = suggestlev;
    }
}