package com.dream.bean;

public class Comment extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentType
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer commenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.storeId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commodityId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentSeq
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private Integer commentseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentTime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentContent
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    private String commentcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentId
     *
     * @return the value of comment.commentId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentId
     *
     * @param commentid the value for comment.commentId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userId
     *
     * @return the value of comment.userId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userId
     *
     * @param userid the value for comment.userId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentType
     *
     * @return the value of comment.commentType
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCommenttype() {
        return commenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentType
     *
     * @param commenttype the value for comment.commentType
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommenttype(Integer commenttype) {
        this.commenttype = commenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.storeId
     *
     * @return the value of comment.storeId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.storeId
     *
     * @param storeid the value for comment.storeId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commodityId
     *
     * @return the value of comment.commodityId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commodityId
     *
     * @param commodityid the value for comment.commodityId
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentSeq
     *
     * @return the value of comment.commentSeq
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public Integer getCommentseq() {
        return commentseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentSeq
     *
     * @param commentseq the value for comment.commentSeq
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommentseq(Integer commentseq) {
        this.commentseq = commentseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentTime
     *
     * @return the value of comment.commentTime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentTime
     *
     * @param commenttime the value for comment.commentTime
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommenttime(String commenttime) {
        this.commenttime = commenttime == null ? null : commenttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentContent
     *
     * @return the value of comment.commentContent
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentContent
     *
     * @param commentcontent the value for comment.commentContent
     *
     * @mbggenerated Fri Oct 03 14:52:46 CST 2014
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }
}