package com.dream.bean;

public class Kinds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kinds.kindsid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private Integer kindsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kinds.kindsname
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private String kindsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kinds.kindsid
     *
     * @return the value of kinds.kindsid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public Integer getKindsid() {
        return kindsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kinds.kindsid
     *
     * @param kindsid the value for kinds.kindsid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setKindsid(Integer kindsid) {
        this.kindsid = kindsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kinds.kindsname
     *
     * @return the value of kinds.kindsname
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public String getKindsname() {
        return kindsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kinds.kindsname
     *
     * @param kindsname the value for kinds.kindsname
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setKindsname(String kindsname) {
        this.kindsname = kindsname == null ? null : kindsname.trim();
    }
}