package com.dream.bean;

public class Store extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storeid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storename
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storedetail
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private String storedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.areaid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storepic
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    private String storepic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storeid
     *
     * @return the value of store.storeid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storeid
     *
     * @param storeid the value for store.storeid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storename
     *
     * @return the value of store.storename
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storename
     *
     * @param storename the value for store.storename
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storedetail
     *
     * @return the value of store.storedetail
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public String getStoredetail() {
        return storedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storedetail
     *
     * @param storedetail the value for store.storedetail
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setStoredetail(String storedetail) {
        this.storedetail = storedetail == null ? null : storedetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.areaid
     *
     * @return the value of store.areaid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.areaid
     *
     * @param areaid the value for store.areaid
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storepic
     *
     * @return the value of store.storepic
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public String getStorepic() {
        return storepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storepic
     *
     * @param storepic the value for store.storepic
     *
     * @mbggenerated Tue Sep 23 17:45:35 CST 2014
     */
    public void setStorepic(String storepic) {
        this.storepic = storepic == null ? null : storepic.trim();
    }
}