package com.dream.dao;

import java.util.List;

import com.dream.bean.Activity;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    Activity selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKey(Activity record);
    
    
	// ******************add by wsg**********************

	/**
	 * 根据条件查询，返回一个list
	 * 
	 * @param activity
	 * @return
	 */
	List<Activity> listActivity(Activity activity);

	/**
	 * 根据条件查询，返回一个对象
	 * 
	 * @param activity
	 * @return
	 */
	Activity detailActivity(Activity activity);
	
}