package com.dream.dao;

import com.dream.bean.Kinds;

public interface KindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    int deleteByPrimaryKey(Integer kindsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    int insert(Kinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    int insertSelective(Kinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    Kinds selectByPrimaryKey(Integer kindsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    int updateByPrimaryKeySelective(Kinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:09:20 CST 2014
     */
    int updateByPrimaryKey(Kinds record);
}