package com.dream.dao;

import java.util.List;

import com.dream.bean.Praise;

public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int deleteByPrimaryKey(Integer praiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insertSelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    Praise selectByPrimaryKey(Integer praiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKeySelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKey(Praise record);
    
    
	// ******************add by wsg**********************

	/**
	 * 根据条件查询，返回一个list
	 * 
	 * @param praise
	 * @return
	 */
	List<Praise> listPraise(Praise praise);

	/**
	 * 根据条件查询，返回一个对象
	 * 
	 * @param praise
	 * @return
	 */
	Praise detailPraise(Praise praise);
	
}