package com.dream.dao;

import java.util.List;

import com.dream.bean.Theme;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int deleteByPrimaryKey(Integer themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    Theme selectByPrimaryKey(Integer themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKeySelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKey(Theme record);

    
	// ******************add by wsg**********************

	/**
	 * 根据条件查询，返回一个list
	 * 
	 * @param theme
	 * @return
	 */
	List<Theme> listTheme(Theme theme);

	/**
	 * 根据条件查询，返回一个对象
	 * 
	 * @param theme
	 * @return
	 */
	Theme detailTheme(Theme theme);
	
	/**
	 * 根据条件统计记录数
	 * @param theme
	 * @return
	 */
	int countTheme(Theme theme);
}