package com.dream.dao;

import java.util.List;

import com.dream.bean.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    Userinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    int updateByPrimaryKey(Userinfo record);

    
	// ******************add by wsg**********************

	/**
	 * 根据条件查询，返回一个list
	 * 
	 * @param userinfo
	 * @return
	 */
	List<Userinfo> listUserinfo(Userinfo userinfo);

	/**
	 * 根据条件查询，返回一个对象
	 * 
	 * @param userinfo
	 * @return
	 */
	Userinfo detailUserinfo(Userinfo userinfo);
	
}