package com.dream.bean;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityname
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activitystarttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activitystarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityendtime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activityendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activitystatus
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activitystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityquota
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activityquota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityaddress
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activityaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activitycreatetime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String activitycreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityid
     *
     * @return the value of activity.activityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityid
     *
     * @param activityid the value for activity.activityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityname
     *
     * @return the value of activity.activityname
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityname
     *
     * @param activityname the value for activity.activityname
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activitystarttime
     *
     * @return the value of activity.activitystarttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivitystarttime() {
        return activitystarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activitystarttime
     *
     * @param activitystarttime the value for activity.activitystarttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivitystarttime(String activitystarttime) {
        this.activitystarttime = activitystarttime == null ? null : activitystarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityendtime
     *
     * @return the value of activity.activityendtime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivityendtime() {
        return activityendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityendtime
     *
     * @param activityendtime the value for activity.activityendtime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivityendtime(String activityendtime) {
        this.activityendtime = activityendtime == null ? null : activityendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activitystatus
     *
     * @return the value of activity.activitystatus
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivitystatus() {
        return activitystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activitystatus
     *
     * @param activitystatus the value for activity.activitystatus
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivitystatus(String activitystatus) {
        this.activitystatus = activitystatus == null ? null : activitystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityquota
     *
     * @return the value of activity.activityquota
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivityquota() {
        return activityquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityquota
     *
     * @param activityquota the value for activity.activityquota
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivityquota(String activityquota) {
        this.activityquota = activityquota == null ? null : activityquota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityaddress
     *
     * @return the value of activity.activityaddress
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivityaddress() {
        return activityaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityaddress
     *
     * @param activityaddress the value for activity.activityaddress
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivityaddress(String activityaddress) {
        this.activityaddress = activityaddress == null ? null : activityaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activitycreatetime
     *
     * @return the value of activity.activitycreatetime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getActivitycreatetime() {
        return activitycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activitycreatetime
     *
     * @param activitycreatetime the value for activity.activitycreatetime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setActivitycreatetime(String activitycreatetime) {
        this.activitycreatetime = activitycreatetime == null ? null : activitycreatetime.trim();
    }
}