package com.dream.bean;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.themeid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer themeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentseq
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer commentseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commenttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentcontent
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private String commentcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentid
     *
     * @return the value of comment.commentid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentid
     *
     * @param commentid the value for comment.commentid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.themeid
     *
     * @return the value of comment.themeid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.themeid
     *
     * @param themeid the value for comment.themeid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setThemeid(Integer themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentseq
     *
     * @return the value of comment.commentseq
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getCommentseq() {
        return commentseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentseq
     *
     * @param commentseq the value for comment.commentseq
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setCommentseq(Integer commentseq) {
        this.commentseq = commentseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commenttime
     *
     * @return the value of comment.commenttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commenttime
     *
     * @param commenttime the value for comment.commenttime
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setCommenttime(String commenttime) {
        this.commenttime = commenttime == null ? null : commenttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentcontent
     *
     * @return the value of comment.commentcontent
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentcontent
     *
     * @param commentcontent the value for comment.commentcontent
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }
}