package com.dream.bean;

import java.util.ArrayList;
import java.util.List;

public class KindsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public KindsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKindsidIsNull() {
            addCriterion("kindsid is null");
            return (Criteria) this;
        }

        public Criteria andKindsidIsNotNull() {
            addCriterion("kindsid is not null");
            return (Criteria) this;
        }

        public Criteria andKindsidEqualTo(Integer value) {
            addCriterion("kindsid =", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidNotEqualTo(Integer value) {
            addCriterion("kindsid <>", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidGreaterThan(Integer value) {
            addCriterion("kindsid >", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("kindsid >=", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidLessThan(Integer value) {
            addCriterion("kindsid <", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidLessThanOrEqualTo(Integer value) {
            addCriterion("kindsid <=", value, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidIn(List<Integer> values) {
            addCriterion("kindsid in", values, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidNotIn(List<Integer> values) {
            addCriterion("kindsid not in", values, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidBetween(Integer value1, Integer value2) {
            addCriterion("kindsid between", value1, value2, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsidNotBetween(Integer value1, Integer value2) {
            addCriterion("kindsid not between", value1, value2, "kindsid");
            return (Criteria) this;
        }

        public Criteria andKindsnameIsNull() {
            addCriterion("kindsname is null");
            return (Criteria) this;
        }

        public Criteria andKindsnameIsNotNull() {
            addCriterion("kindsname is not null");
            return (Criteria) this;
        }

        public Criteria andKindsnameEqualTo(String value) {
            addCriterion("kindsname =", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameNotEqualTo(String value) {
            addCriterion("kindsname <>", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameGreaterThan(String value) {
            addCriterion("kindsname >", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameGreaterThanOrEqualTo(String value) {
            addCriterion("kindsname >=", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameLessThan(String value) {
            addCriterion("kindsname <", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameLessThanOrEqualTo(String value) {
            addCriterion("kindsname <=", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameLike(String value) {
            addCriterion("kindsname like", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameNotLike(String value) {
            addCriterion("kindsname not like", value, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameIn(List<String> values) {
            addCriterion("kindsname in", values, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameNotIn(List<String> values) {
            addCriterion("kindsname not in", values, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameBetween(String value1, String value2) {
            addCriterion("kindsname between", value1, value2, "kindsname");
            return (Criteria) this;
        }

        public Criteria andKindsnameNotBetween(String value1, String value2) {
            addCriterion("kindsname not between", value1, value2, "kindsname");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidIsNull() {
            addCriterion("secondkindsid is null");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidIsNotNull() {
            addCriterion("secondkindsid is not null");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidEqualTo(String value) {
            addCriterion("secondkindsid =", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidNotEqualTo(String value) {
            addCriterion("secondkindsid <>", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidGreaterThan(String value) {
            addCriterion("secondkindsid >", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidGreaterThanOrEqualTo(String value) {
            addCriterion("secondkindsid >=", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidLessThan(String value) {
            addCriterion("secondkindsid <", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidLessThanOrEqualTo(String value) {
            addCriterion("secondkindsid <=", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidLike(String value) {
            addCriterion("secondkindsid like", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidNotLike(String value) {
            addCriterion("secondkindsid not like", value, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidIn(List<String> values) {
            addCriterion("secondkindsid in", values, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidNotIn(List<String> values) {
            addCriterion("secondkindsid not in", values, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidBetween(String value1, String value2) {
            addCriterion("secondkindsid between", value1, value2, "secondkindsid");
            return (Criteria) this;
        }

        public Criteria andSecondkindsidNotBetween(String value1, String value2) {
            addCriterion("secondkindsid not between", value1, value2, "secondkindsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kinds
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 30 16:06:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kinds
     *
     * @mbggenerated Thu Oct 30 16:06:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}