package com.dream.bean;

public class Praise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.praiseid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer praiseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.praiseiduserid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer praiseiduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.praiseidactivityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    private Integer praiseidactivityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.praiseid
     *
     * @return the value of praise.praiseid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getPraiseid() {
        return praiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.praiseid
     *
     * @param praiseid the value for praise.praiseid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setPraiseid(Integer praiseid) {
        this.praiseid = praiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.praiseiduserid
     *
     * @return the value of praise.praiseiduserid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getPraiseiduserid() {
        return praiseiduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.praiseiduserid
     *
     * @param praiseiduserid the value for praise.praiseiduserid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setPraiseiduserid(Integer praiseiduserid) {
        this.praiseiduserid = praiseiduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.praiseidactivityid
     *
     * @return the value of praise.praiseidactivityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public Integer getPraiseidactivityid() {
        return praiseidactivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.praiseidactivityid
     *
     * @param praiseidactivityid the value for praise.praiseidactivityid
     *
     * @mbggenerated Mon Oct 27 23:55:35 CST 2014
     */
    public void setPraiseidactivityid(Integer praiseidactivityid) {
        this.praiseidactivityid = praiseidactivityid;
    }
}